server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: gateway/logging
          uri: http://127.0.0.1:4567
          predicates:
            - Path=/gateway/logging/**
          filters:
            - StripPrefix=2


services:
  logging:
    uri: http://127.0.0.1:4567